import type { Customer } from "@/types/customer";

export const CUSTOMERS: Customer[] = [
  {
    id: "U001",
    name: "Sarah Johnson",
    email: "sarah.j@email.com",
    phone: "(555) 123-4567",
    address: "Brooklyn, NY",
    orders: 15,
    total: 597.55,
    lastOrder: "Jun 28",
    hasNote: true,
    status: "active",
    orderHistory: [
      {
        id: "ORD-1042",
        date: "Jun 28, 2026",
        items: 4,
        total: 86.4,
        status: "Delivered",
      },
      {
        id: "ORD-1018",
        date: "Jun 14, 2026",
        items: 3,
        total: 52.1,
        status: "Delivered",
      },
      {
        id: "ORD-0991",
        date: "May 30, 2026",
        items: 5,
        total: 74.25,
        status: "Delivered",
      },
    ],
  },
  {
    id: "U002",
    name: "Michael Chen",
    email: "m.chen@email.com",
    phone: "(555) 234-5678",
    address: "Manhattan, NY",
    orders: 8,
    total: 342.0,
    lastOrder: "Jun 25",
    hasNote: true,
    status: "active",
    orderHistory: [
      {
        id: "ORD-1035",
        date: "Jun 25, 2026",
        items: 2,
        total: 41.5,
        status: "Delivered",
      },
      {
        id: "ORD-1002",
        date: "Jun 8, 2026",
        items: 3,
        total: 63.0,
        status: "Delivered",
      },
    ],
  },
  {
    id: "U003",
    name: "Emily Rodriguez",
    email: "emily.r@email.com",
    phone: "(555) 345-6789",
    address: "Queens, NY",
    orders: 12,
    total: 489.25,
    lastOrder: "Jun 22",
    hasNote: false,
    status: "active",
    orderHistory: [
      {
        id: "ORD-1029",
        date: "Jun 22, 2026",
        items: 6,
        total: 98.75,
        status: "Processing",
      },
      {
        id: "ORD-1007",
        date: "Jun 5, 2026",
        items: 2,
        total: 36.2,
        status: "Delivered",
      },
    ],
  },
  {
    id: "U004",
    name: "David Thompson",
    email: "d.thompson@email.com",
    phone: "(555) 456-7890",
    address: "Bronx, NY",
    orders: 6,
    total: 215.8,
    lastOrder: "Jun 20",
    hasNote: true,
    status: "active",
    orderHistory: [
      {
        id: "ORD-1021",
        date: "Jun 20, 2026",
        items: 3,
        total: 48.9,
        status: "Delivered",
      },
    ],
  },
  {
    id: "U005",
    name: "Jessica Martinez",
    email: "j.martinez@email.com",
    phone: "(555) 567-8901",
    address: "Staten Island, NY",
    orders: 3,
    total: 98.5,
    lastOrder: "May 15",
    hasNote: false,
    status: "inactive",
    orderHistory: [
      {
        id: "ORD-0955",
        date: "May 15, 2026",
        items: 2,
        total: 32.5,
        status: "Delivered",
      },
      {
        id: "ORD-0910",
        date: "Apr 2, 2026",
        items: 1,
        total: 18.0,
        status: "Cancelled",
      },
    ],
  },
  {
    id: "U006",
    name: "Robert Lee",
    email: "robert.lee@email.com",
    phone: "(555) 678-9012",
    address: "Brooklyn, NY",
    orders: 2,
    total: 67.25,
    lastOrder: "Apr 30",
    hasNote: false,
    status: "inactive",
    orderHistory: [
      {
        id: "ORD-0933",
        date: "Apr 30, 2026",
        items: 2,
        total: 39.25,
        status: "Delivered",
      },
    ],
  },
];
