import type { Distributor } from "@/types/distributor";

export const DISTRIBUTORS: Distributor[] = [
  {
    id: "S001",
    name: "4PF Co.",
    paymentTerms: "NET-30",
    contact: "Marcus Chen",
    phone: "(415) 555-0142",
    categories: ["Fruits", "Vegetables", "Protein"],
    location: "San Francisco, CA",
    delivery: "Mon, Wed 8:00 AM",
    items: 3,
    docs: null,
    products: [
      {
        id: "P001",
        name: "Organic Gala Apples",
        product: "Apples",
        source: "FreshMarket Co.",
        price: 54,
        qty: 12,
        unit: "Box",
        category: "Fruits",
      },
      {
        id: "P002",
        name: "Baby Carrots",
        product: "Carrots",
        source: "James Farms",
        price: 38.4,
        qty: 24,
        unit: "Pound",
        category: "Vegetables",
      },
      {
        id: "P003",
        name: "Roma Tomatoes",
        product: "Tomatoes",
        source: "Alpine Products Co.",
        price: 33.6,
        qty: 20,
        unit: "Pound",
        category: "Vegetables",
      },
    ],
  },
  {
    id: "S002",
    name: "GreenLeaf Supply",
    paymentTerms: "NET-15",
    contact: "Priya Patel",
    phone: "(510) 555-0198",
    categories: ["Vegetables", "Herbs"],
    location: "Oakland, CA",
    delivery: "Tue, Thu 9:00 AM",
    items: 5,
    docs: null,
    products: [
      {
        id: "P004",
        name: "Fresh Basil",
        product: "Basil",
        source: "Herb Grove",
        price: 6,
        qty: 1,
        unit: "Bunch",
        category: "Herbs",
      },
      {
        id: "P005",
        name: "Organic Kale",
        product: "Kale",
        source: "GreenLeaf Supply",
        price: 2.9,
        qty: 1,
        unit: "Pound",
        category: "Vegetables",
      },
    ],
  },
  {
    id: "S003",
    name: "Pacific Protein",
    paymentTerms: "NET-45",
    contact: "David Park",
    phone: "(628) 555-0177",
    categories: ["Protein"],
    location: "San Jose, CA",
    delivery: "Fri 7:30 AM",
    items: 4,
    docs: null,
    products: [
      {
        id: "P006",
        name: "Chicken Breast Pack",
        product: "Chicken Breast",
        source: "Pacific Protein",
        price: 8.5,
        qty: 1,
        unit: "Pound",
        category: "Protein",
      },
    ],
  },
  {
    id: "S004",
    name: "Bay Dairy Co.",
    paymentTerms: "NET-30",
    contact: "Elena Rossi",
    phone: "(415) 555-0110",
    categories: ["Dairy"],
    location: "Petaluma, CA",
    delivery: "Mon, Fri 6:00 AM",
    items: 6,
    docs: null,
    products: [
      {
        id: "P007",
        name: "Whole Milk Gallon",
        product: "Whole Milk",
        source: "Bay Dairy Co.",
        price: 4.25,
        qty: 1,
        unit: "Gallon",
        category: "Dairy",
      },
    ],
  },
  {
    id: "S005",
    name: "Coastal Catch",
    paymentTerms: "NET-7",
    contact: "James Okonkwo",
    phone: "(831) 555-0164",
    categories: ["Protein", "Seafood"],
    location: "Monterey, CA",
    delivery: "Wed 5:00 AM",
    items: 2,
    docs: null,
    products: [
      {
        id: "P008",
        name: "Salmon Fillet",
        product: "Salmon Fillet",
        source: "Coastal Catch",
        price: 14,
        qty: 1,
        unit: "Pound",
        category: "Seafood",
      },
    ],
  },
];
