import type { Distributor } from "@/types/distributor";

export const DISTRIBUTORS: Distributor[] = [
  {
    id: "DIS-10001",
    name: "4PF",
    paymentTerms: "NET-30",
    contact: "Marcus Chen",
    phone: "(415) 234-5678",
    location: "Los Angeles, CA",
    fullAddress: "1845 S La Cienega Blvd, Los Angeles, CA 90035",
    delivery: "Mon, Wed 8:00 AM",
    deliveryDays: [
      { day: "Mon", time: "08:00" },
      { day: "Wed", time: "08:00" },
    ],
    documents: [
      {
        id: "D001",
        name: "Order 4 _ Milestone 3.pdf",
        size: "560.4 KB",
      },
    ],
    notes:
      "Preferred drop-off is the loading dock on La Cienega. Call 15 minutes before arrival.",
    contacts: [
      {
        id: "C001",
        firstName: "Marcus",
        lastName: "Chen",
        phone: "(415) 234-5678",
        email: "marcus@4pf.com",
        title: "Manager",
        primary: true,
      },
      {
        id: "C002",
        firstName: "Arkadi",
        lastName: "Dumikyan",
        phone: "808 393 0043",
        email: "james@freshmarket",
        title: "Junior Manager",
        primary: false,
      },
    ],
    categories: ["Fruits", "Vegetables", "Protein"],
    items: 3,
    docs: "1",
    products: [
      {
        id: "P001",
        name: "Organic Gala Apples",
        product: "Apples",
        source: "FreshMarket Co.",
        price: 54,
        qty: 12,
        unit: "Box",
        category: "Fruits",
      },
      {
        id: "P002",
        name: "Baby Carrots",
        product: "Carrots",
        source: "James Farms",
        price: 38.4,
        qty: 24,
        unit: "Pound",
        category: "Vegetables",
      },
      {
        id: "P003",
        name: "Roma Tomatoes",
        product: "Tomatoes",
        source: "Alpine Products Co.",
        price: 33.6,
        qty: 20,
        unit: "Pound",
        category: "Vegetables",
      },
    ],
  },
  {
    id: "DIS-10002",
    name: "FreshFood LLC",
    paymentTerms: "NET-10",
    contact: "Priya Patel",
    phone: "(510) 555-0198",
    location: "Oakland, CA",
    fullAddress: "2101 Broadway, Oakland, CA 94612",
    delivery: "Tue, Thu 9:00 AM",
    deliveryDays: [
      { day: "Tue", time: "09:00" },
      { day: "Thu", time: "09:00" },
    ],
    documents: [],
    notes: "Leave coolers stacked by the side entrance. Do not ring the front bell.",
    contacts: [
      {
        id: "C003",
        firstName: "Priya",
        lastName: "Patel",
        phone: "(510) 555-0198",
        email: "priya@freshfood.co",
        title: "Manager",
        primary: true,
      },
    ],
    categories: ["Vegetables", "Herbs"],
    items: 5,
    docs: null,
    products: [
      {
        id: "P004",
        name: "Fresh Basil",
        product: "Basil",
        source: "Herb Grove",
        price: 6,
        qty: 1,
        unit: "Bunch",
        category: "Herbs",
      },
      {
        id: "P005",
        name: "Organic Kale",
        product: "Kale",
        source: "GreenLeaf Supply",
        price: 2.9,
        qty: 1,
        unit: "Pound",
        category: "Vegetables",
      },
    ],
  },
  {
    id: "DIS-10003",
    name: "Pacific Protein",
    paymentTerms: "NET-35",
    contact: "David Park",
    phone: "(628) 555-0177",
    location: "San Jose, CA",
    fullAddress: "88 S 1st St, San Jose, CA 95113",
    delivery: "Fri 7:30 AM",
    deliveryDays: [{ day: "Fri", time: "07:30" }],
    documents: [
      { id: "D002", name: "Insurance_COI.pdf", size: "220.1 KB" },
    ],
    notes:
      "Lorem ipsum dolor se amat amore and the fruits from inventory should be lorem ipsum dilomana amitor",
    contacts: [
      {
        id: "C004",
        firstName: "David",
        lastName: "Park",
        phone: "(628) 555-0177",
        email: "david@pacificprotein.com",
        title: "Operations",
        primary: true,
      },
    ],
    categories: ["Protein"],
    items: 4,
    docs: "1",
    products: [
      {
        id: "P006",
        name: "Chicken Breast Pack",
        product: "Chicken Breast",
        source: "Pacific Protein",
        price: 8.5,
        qty: 1,
        unit: "Pound",
        category: "Protein",
      },
    ],
  },
  {
    id: "DIS-10004",
    name: "Bay Dairy Co.",
    paymentTerms: "NET-30",
    contact: "Elena Rossi",
    phone: "(415) 555-0110",
    location: "Los Angeles, CA",
    fullAddress: "1200 Vine St, Los Angeles, CA 90028",
    delivery: "Mon, Fri 6:00 AM",
    deliveryDays: [
      { day: "Mon", time: "06:00" },
      { day: "Fri", time: "06:00" },
    ],
    documents: [],
    notes: "Dairy must stay on the refrigerated truck until a receiver signs.",
    contacts: [
      {
        id: "C005",
        firstName: "Elena",
        lastName: "Rossi",
        phone: "(415) 555-0110",
        email: "elena@baydairy.com",
        title: "Manager",
        primary: true,
      },
    ],
    categories: ["Dairy"],
    items: 6,
    docs: null,
    products: [
      {
        id: "P007",
        name: "Whole Milk Gallon",
        product: "Whole Milk",
        source: "Bay Dairy Co.",
        price: 4.25,
        qty: 1,
        unit: "Gallon",
        category: "Dairy",
      },
    ],
  },
  {
    id: "DIS-10005",
    name: "Coastal Catch",
    paymentTerms: "NET-15",
    contact: "James Okonkwo",
    phone: "(831) 555-0164",
    location: "Monterey, CA",
    fullAddress: "32 Cannery Row, Monterey, CA 93940",
    delivery: "Wed 5:00 AM",
    deliveryDays: [{ day: "Wed", time: "05:00" }],
    documents: [
      { id: "D003", name: "Catch_Certificate.pdf", size: "104.8 KB" },
    ],
    notes: "Seafood arrives packed on ice. Confirm cooler count before unloading.",
    contacts: [
      {
        id: "C006",
        firstName: "James",
        lastName: "Okonkwo",
        phone: "(831) 555-0164",
        email: "james@coastalcatch.com",
        title: "Manager",
        primary: true,
      },
    ],
    categories: ["Protein", "Seafood"],
    items: 2,
    docs: "1",
    products: [
      {
        id: "P008",
        name: "Salmon Fillet",
        product: "Salmon Fillet",
        source: "Coastal Catch",
        price: 14,
        qty: 1,
        unit: "Pound",
        category: "Seafood",
      },
    ],
  },
];
