import type { Distributor } from "@/types/distributor";

export const DISTRIBUTORS: Distributor[] = [
  {
    id: "S001",
    name: "4PF Co.",
    paymentTerms: "NET-30",
    contact: "Marcus Chen",
    phone: "(415) 555-0142",
    categories: ["Fruits", "Vegetables"],
    location: "San Francisco, CA",
    delivery: "Mon, Wed 8:00 AM",
    items: 3,
    docs: null,
    products: [
      {
        id: "P001",
        name: "Apples",
        source: "FreshMarket Co.",
        price: 4.5,
        unit: "lb",
        category: "Fruits",
        lastUpdate: "Jul 1, 2026 1:15 PM",
        updatedByAvatar: true,
      },
      {
        id: "P002",
        name: "Carrots",
        source: "Valley Farms",
        price: 2.25,
        unit: "lb",
        category: "Vegetables",
        lastUpdate: "Jun 28, 2026 10:40 AM",
      },
      {
        id: "P003",
        name: "Tomatoes",
        source: "FreshMarket Co.",
        price: 3.75,
        unit: "lb",
        category: "Vegetables",
        lastUpdate: "Jun 30, 2026 4:05 PM",
      },
    ],
  },
  {
    id: "S002",
    name: "GreenLeaf Supply",
    paymentTerms: "NET-15",
    contact: "Priya Patel",
    phone: "(510) 555-0198",
    categories: ["Vegetables", "Herbs"],
    location: "Oakland, CA",
    delivery: "Tue, Thu 9:00 AM",
    items: 5,
    docs: null,
    products: [
      {
        id: "P004",
        name: "Basil",
        source: "Herb Grove",
        price: 6.0,
        unit: "bunch",
        category: "Herbs",
        lastUpdate: "Jun 29, 2026 2:20 PM",
      },
      {
        id: "P005",
        name: "Kale",
        source: "GreenLeaf Supply",
        price: 2.9,
        unit: "lb",
        category: "Vegetables",
        lastUpdate: "Jul 1, 2026 9:10 AM",
      },
    ],
  },
  {
    id: "S003",
    name: "Pacific Protein",
    paymentTerms: "NET-45",
    contact: "David Park",
    phone: "(628) 555-0177",
    categories: ["Protein"],
    location: "San Jose, CA",
    delivery: "Fri 7:30 AM",
    items: 4,
    docs: null,
    products: [
      {
        id: "P006",
        name: "Chicken Breast",
        source: "Pacific Protein",
        price: 8.5,
        unit: "lb",
        category: "Protein",
        lastUpdate: "Jun 27, 2026 11:00 AM",
      },
    ],
  },
  {
    id: "S004",
    name: "Bay Dairy Co.",
    paymentTerms: "NET-30",
    contact: "Elena Rossi",
    phone: "(415) 555-0110",
    categories: ["Dairy"],
    location: "Petaluma, CA",
    delivery: "Mon, Fri 6:00 AM",
    items: 6,
    docs: null,
    products: [
      {
        id: "P007",
        name: "Whole Milk",
        source: "Bay Dairy Co.",
        price: 4.25,
        unit: "gal",
        category: "Dairy",
        lastUpdate: "Jul 1, 2026 8:45 AM",
      },
    ],
  },
  {
    id: "S005",
    name: "Coastal Catch",
    paymentTerms: "NET-7",
    contact: "James Okonkwo",
    phone: "(831) 555-0164",
    categories: ["Protein", "Seafood"],
    location: "Monterey, CA",
    delivery: "Wed 5:00 AM",
    items: 2,
    docs: null,
    products: [
      {
        id: "P008",
        name: "Salmon Fillet",
        source: "Coastal Catch",
        price: 14.0,
        unit: "lb",
        category: "Seafood",
        lastUpdate: "Jun 26, 2026 3:30 PM",
      },
    ],
  },
];
