import type { Item } from "@/types/item";

const DESC =
  "Hand-selected for peak ripeness and flavor. Ideal for retail and foodservice with consistent sizing and excellent shelf life.";

function photo(id: string, label: string, bg: string): Item["photos"][number] {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="96" height="96" viewBox="0 0 96 96"><rect width="96" height="96" rx="12" fill="${bg}"/><text x="48" y="54" text-anchor="middle" font-family="Arial,sans-serif" font-size="16" font-weight="700" fill="#FFFFFF">${label}</text></svg>`;
  return {
    id,
    url: `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`,
    name: `${label.toLowerCase()}.png`,
  };
}

function placeholder(id: string): Item["photos"][number] {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="96" height="96" viewBox="0 0 96 96"><rect width="96" height="96" rx="12" fill="#F3E6A8"/><path d="M28 62l12-16 10 12 8-8 14 12H28z" fill="#D4C56A"/><circle cx="38" cy="36" r="6" fill="#D4C56A"/></svg>`;
  return {
    id,
    url: `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`,
    name: "placeholder.png",
  };
}

export const ITEMS: Item[] = [
  {
    id: "IT-000001",
    name: "Tasty Armenian Peach",
    merchandisingName: "Tasty Armenian Peach",
    description: DESC,
    preorderInfo: "",
    category: "Fruits",
    subcategory: "Stone",
    distributor: "4PF",
    source: "FreshMarket Co",
    buyingUnit: "Case/Box",
    buyingPrice: 48,
    contents: 12,
    singleItemUnit: "1 lb",
    sellingPrice: 12,
    photos: [placeholder("p1")],
  },
  {
    id: "IT-000002",
    name: "Organic Strawberries",
    merchandisingName: "Organic Strawberries",
    description: DESC,
    preorderInfo: "",
    category: "Fruits",
    subcategory: "Berry",
    distributor: "FreshFood LLC",
    source: "NanasFruits",
    buyingUnit: "Case/Box",
    buyingPrice: 36,
    contents: 8,
    singleItemUnit: "1 lb",
    sellingPrice: 9,
    photos: [placeholder("p2")],
  },
  {
    id: "IT-000003",
    name: "Wagyu Tenderloin Steak",
    merchandisingName: "Wagyu Aged Tenderloin Steak",
    description:
      "Premium wagyu tenderloin with deep marbling and buttery texture. Aged for richness and cut for consistent portioning.",
    preorderInfo: "Requires 48-hour pre-order notice.",
    category: "Protein",
    subcategory: "Meat",
    distributor: "4PF",
    source: "MeatFactory Co",
    buyingUnit: "Case/Box",
    buyingPrice: 270.6,
    contents: 16,
    singleItemUnit: "1 steak (12 oz)",
    sellingPrice: 29,
    photos: [
      photo("p3a", "W1", "#8B3A3A"),
      photo("p3b", "W2", "#A04848"),
      photo("p3c", "W3", "#6E2E2E"),
    ],
  },
  {
    id: "IT-000004",
    name: "Baby Spinach",
    merchandisingName: "Baby Spinach",
    description: DESC,
    preorderInfo: "",
    category: "Vegetables",
    subcategory: "Leafy",
    distributor: "FreshFood LLC",
    source: "Alpine Products Co.",
    buyingUnit: "Case/Box",
    buyingPrice: 24,
    contents: 12,
    singleItemUnit: "Bunch",
    sellingPrice: 4,
    photos: [placeholder("p4")],
  },
  {
    id: "IT-000005",
    name: "Jasmine Rice",
    merchandisingName: "Jasmine Rice",
    description: DESC,
    preorderInfo: "",
    category: "Grain",
    subcategory: "Rice",
    distributor: "Pacific Protein",
    source: "Alpine Products Co.",
    buyingUnit: "Bag",
    buyingPrice: 42,
    contents: 20,
    singleItemUnit: "1 lb",
    sellingPrice: 3.5,
    photos: [placeholder("p5")],
  },
  {
    id: "IT-000006",
    name: "Extra Virgin Olive Oil",
    merchandisingName: "Extra Virgin Olive Oil",
    description: DESC,
    preorderInfo: "",
    category: "Pantry",
    subcategory: "Oil",
    distributor: "Bay Dairy Co.",
    source: "FreshMarket Co",
    buyingUnit: "Case/Box",
    buyingPrice: 60,
    contents: 6,
    singleItemUnit: "Each",
    sellingPrice: 18,
    photos: [placeholder("p6")],
  },
  {
    id: "IT-000007",
    name: "Heirloom Tomatoes",
    merchandisingName: "Heirloom Tomatoes",
    description: DESC,
    preorderInfo: "",
    category: "Vegetables",
    subcategory: "Nightshade",
    distributor: "4PF",
    source: "FreshMarket Co",
    buyingUnit: "Crate",
    buyingPrice: 55,
    contents: 10,
    singleItemUnit: "1 lb",
    sellingPrice: 8,
    photos: [placeholder("p7")],
  },
  {
    id: "IT-000008",
    name: "Farm Eggs",
    merchandisingName: "Farm Fresh Eggs",
    description: DESC,
    preorderInfo: "",
    category: "Protein",
    subcategory: "Eggs",
    distributor: "FreshFood LLC",
    source: "MeatWorld",
    buyingUnit: "Case/Box",
    buyingPrice: 40,
    contents: 15,
    singleItemUnit: "Dozen",
    sellingPrice: 6,
    photos: [placeholder("p8")],
  },
  {
    id: "IT-000009",
    name: "Angus Chuck Ground Beef",
    merchandisingName: "Angus Chuck Ground Beef",
    description: DESC,
    preorderInfo: "",
    category: "Protein",
    subcategory: "Meat",
    distributor: "4PF",
    source: "FreshMarket Co",
    buyingUnit: "Case/Box",
    buyingPrice: 180,
    contents: 12,
    singleItemUnit: "1 lb",
    sellingPrice: 29,
    photos: [
      photo("p9a", "B1", "#7A3B3B"),
      photo("p9b", "B2", "#944848"),
    ],
  },
  {
    id: "IT-000010",
    name: "Rib-eye Steak",
    merchandisingName: "Rib-eye Steak",
    description: DESC,
    preorderInfo: "",
    category: "Protein",
    subcategory: "Meat",
    distributor: "4PF",
    source: "FreshMarket Co",
    buyingUnit: "Case/Box",
    buyingPrice: 220,
    contents: 10,
    singleItemUnit: "1 steak (12 oz)",
    sellingPrice: 29,
    photos: [photo("p10", "RE", "#8B3A3A")],
  },
  {
    id: "IT-000011",
    name: "Legion Fields Whole Chicken",
    merchandisingName: "Legion Fields Whole Chicken",
    description: DESC,
    preorderInfo: "",
    category: "Protein",
    subcategory: "Poultry",
    distributor: "4PF",
    source: "FreshMarket Co",
    buyingUnit: "Case/Box",
    buyingPrice: 96,
    contents: 8,
    singleItemUnit: "Each",
    sellingPrice: 29,
    photos: [placeholder("p11")],
  },
  {
    id: "IT-000012",
    name: "Allen Brothers Drumsticks",
    merchandisingName: "Allen Brothers Drumsticks",
    description: DESC,
    preorderInfo: "",
    category: "Protein",
    subcategory: "Poultry",
    distributor: "4PF",
    source: "FreshMarket Co",
    buyingUnit: "Case/Box",
    buyingPrice: 72,
    contents: 12,
    singleItemUnit: "1 lb",
    sellingPrice: 29,
    photos: [placeholder("p12")],
  },
  {
    id: "IT-000013",
    name: "Free Bird Chicken Breasts",
    merchandisingName: "Free Bird Chicken Breasts",
    description: DESC,
    preorderInfo: "",
    category: "Protein",
    subcategory: "Poultry",
    distributor: "Pacific Protein",
    source: "FreshMarket Co",
    buyingUnit: "Case/Box",
    buyingPrice: 88,
    contents: 10,
    singleItemUnit: "1 lb",
    sellingPrice: 24,
    photos: [placeholder("p13")],
  },
  {
    id: "IT-000014",
    name: "Arctic Char",
    merchandisingName: "Artic Char",
    description: DESC,
    preorderInfo: "",
    category: "Protein",
    subcategory: "Seafood",
    distributor: "4PF",
    source: "FreshMarket Co",
    buyingUnit: "Case/Box",
    buyingPrice: 140,
    contents: 8,
    singleItemUnit: "1 lb",
    sellingPrice: 29,
    photos: [placeholder("p14")],
  },
  {
    id: "IT-000015",
    name: "Wild Salmon",
    merchandisingName: "Wild Salmon",
    description: DESC,
    preorderInfo: "",
    category: "Protein",
    subcategory: "Seafood",
    distributor: "4PF",
    source: "FreshMarket Co",
    buyingUnit: "Case/Box",
    buyingPrice: 160,
    contents: 8,
    singleItemUnit: "1 lb",
    sellingPrice: 29,
    photos: [placeholder("p15")],
  },
  {
    id: "IT-000016",
    name: "Tasty Apples",
    merchandisingName: "Tasty Apples",
    description: DESC,
    preorderInfo: "",
    category: "Fruits",
    subcategory: "Other",
    distributor: "FreshFood LLC",
    source: "NanasFruits",
    buyingUnit: "Case/Box",
    buyingPrice: 40,
    contents: 20,
    singleItemUnit: "1 lb",
    sellingPrice: 5,
    photos: [placeholder("p16")],
  },
];
